---
- name: overlayfs directories
  file:
      path: "{{ ansible_user_dir }}/.overlay/{{ item }}"
      state: directory
  with_items:
      - artery-host
      - artery-upper
      - artery-work

- name: mount artery-host
  mount:
    path: "{{ ansible_user_dir }}/.overlay/artery-host"
    src: vagrant
    fstype: vboxsf
    opts: uid={{ ansible_user_uid }},gid={{ ansible_user_gid }}
    state: mounted
  become: yes

- name: mountpoint for overlayfs
  file:
      path: "{{ ansible_user_dir }}/artery"
      state: directory

- name: mount overlay filesystem
  mount:
      path: "{{ ansible_user_dir }}/artery"
      src: overlay
      fstype: overlay
      opts: "lowerdir={{ ansible_user_dir }}/.overlay/artery-host,\
             upperdir={{ ansible_user_dir }}/.overlay/artery-upper,\
             workdir={{ ansible_user_dir }}/.overlay/artery-work,\
             x-systemd.requires-mounts-for={{ ansible_user_dir }}/.overlay/artery-host"
      state: mounted
  become: yes
